In [8]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
arr1 = np.array(range(10))#시쿼스데이터 
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr3 = np.array(['a','b','c'])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [12]:
arr2 =  np.array([0.1,0.2,0.3])
arr2

array([0.1, 0.2, 0.3])

In [13]:
arr4 = np.array([1,2,'a','b',0.1,0.2])
arr4

array(['1', '2', 'a', 'b', '0.1', '0.2'], dtype='<U11')

In [15]:
arr5 = np.array([1,2,0.3,0.4])#input정수지만 실수형으로 형변환
arr5

array([1. , 2. , 0.3, 0.4])

In [17]:
arr6 = np.array(
[[1,2,3],
[4,5,6],
 [7,8,9]])
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr1.dtype#32는 비트수 

dtype('int32')

In [21]:
arr2.dtype

dtype('float64')

In [22]:
arr3.dtype

dtype('<U1')

In [23]:
print(arr4.dtype)

<U11


In [25]:
print(arr5.dtype)
arr5

float64


array([1. , 2. , 0.3, 0.4])

# shape
* 배열의 형태

In [26]:
arr5

array([1. , 2. , 0.3, 0.4])

arr5.shape

In [27]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr6.shape#형과 열..

(3, 3)

# arange

In [31]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr2 = np.arange(3,13)
arr2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
arr3 = np.arange(5.0)
arr3

array([0., 1., 2., 3., 4.])

In [37]:
arr4 = np.arange(3, 100, 3.0)
arr4

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39.,
       42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72., 75., 78.,
       81., 84., 87., 90., 93., 96., 99.])

# linspace

In [39]:
np.linspace(-5,5,10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

### reshape(배열의 형변 변환)

In [42]:
arr = np.arange(36.0)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [43]:
arr.shape

(36,)

In [45]:
arr3 = arr.reshape(12,3)
arr3

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.],
       [24., 25., 26.],
       [27., 28., 29.],
       [30., 31., 32.],
       [33., 34., 35.]])

In [49]:
arr3.shape

(12, 3)

In [52]:
# 3 dimension
arr3 =  arr.reshape(3,4,3)
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [55]:
print(arr1.shape)

(10,)


In [57]:
arr1.shape = (5,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### astype - 배열의 dtype 변환

In [60]:
# -1 shape
print(arr3.shape)
arr3


(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [61]:
arr3.reshape(-1,12)#행열에서 한 곳만 정해줌

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.]])

In [62]:
arr3.reshape(-1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [63]:
arr3.reshape(4, -1,3)

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]],

       [[27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [66]:
arr1 = np.arange(5)
arr2 = np.arange(0.0,0.5,0.1)

In [67]:
arr1, arr2

(array([0, 1, 2, 3, 4]), array([0. , 0.1, 0.2, 0.3, 0.4]))

In [69]:
print(arr1.dtype)
print(arr2.dtype)

int32
float64


In [70]:
arr1.astype(float)

array([0., 1., 2., 3., 4.])

In [71]:
print(arr1.astype(np.float64))

[0. 1. 2. 3. 4.]


In [74]:
# float -> char
print(arr2.astype(str))
print(arr2.astype(np.str))

['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']
['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']


#rand

In [75]:
np.random.rand(5)

array([0.00731837, 0.83939673, 0.27282565, 0.84384406, 0.04088841])

In [76]:
np.random.rand(3, 3)

array([[0.38261841, 0.33608897, 0.24991788],
       [0.23911351, 0.44882785, 0.44753696],
       [0.28221829, 0.29002562, 0.95366542]])

In [77]:
np.random.rand(2,2,2)

array([[[0.02293083, 0.5930283 ],
        [0.49884767, 0.60897292]],

       [[0.90212284, 0.64164399],
        [0.98755539, 0.27309998]]])

### randint

In [79]:
np.random.randint(-5,3,(3,3))

array([[-3,  0,  1],
       [-3, -1, -1],
       [ 0,  1,  0]])

In [81]:
np.random.randn(2,5)

array([[-0.54778245,  1.0796182 ,  0.48024744, -1.74025922,  0.74563301],
       [ 0.09736447, -0.26571226,  0.2754078 , -0.05979192,  0.19680685]])

# array의 indexing,slicing

In [86]:
arr1 =  np.arange(0, 100, 10.0)
arr1

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [87]:
arr1[0]

0.0

In [89]:
arr1[-1]
arr1[5]

50.0

In [91]:
arr1[:], arr1[4:], arr1[1:]

(array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]),
 array([40., 50., 60., 70., 80., 90.]),
 array([10., 20., 30., 40., 50., 60., 70., 80., 90.]))

# n-Dim Array indexing slicing

In [98]:
#2차원 배열:0~23 (8,3)의 배열을 만드세요 dtype=float
arr2 = np.arange(24.0).reshape(8,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [99]:
arr2[0], arr2[4], arr2[3][1]

(array([0., 1., 2.]), array([12., 13., 14.]), 10.0)

In [100]:
print(arr2[3][1]) #성능이 조금 느려요
print(arr2[3,1])

10.0
10.0


In [106]:
print(arr2[3,1:])
print(arr2[3:,1:])#row cloumn
print(arr2[::2,: ])

[10. 11.]
[[10. 11.]
 [13. 14.]
 [16. 17.]
 [19. 20.]
 [22. 23.]]
[[ 0.  1.  2.]
 [ 6.  7.  8.]
 [12. 13. 14.]
 [18. 19. 20.]]


In [111]:
print(arr2[[0, 5,3]])
print('-'*10)
print(arr2[
    [0,5,3],[1]
])

[[ 0.  1.  2.]
 [15. 16. 17.]
 [ 9. 10. 11.]]
----------
[ 1. 16. 10.]


In [113]:
arr2[arr2>10]

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [115]:
arr2[arr2%2==1]

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.])

### numpy의 상수

In [120]:
arr = np.array([1,2,3, np.nan, np.inf, -np.inf])#nan은 
print('dtype: ',arr.dtype)
arr

dtype:  float64


array([  1.,   2.,   3.,  nan,  inf, -inf])

### arr의 연산

In [123]:
arr1 = np.arange(0, 10, 1)
arr2 = np.arange(1,0,-0.1)
arr1, arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]))

In [124]:
# array 와 scalar 연산 scalar을 해당 arry만큼 확장시켜서 broadcasting
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
arr1 + 1, arr1 + [1,1,1,1,1,1,1,1,1,1]

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [130]:
print(arr1-1)
print(arr1 * 10)
print(arr1 / 10)
print(arr1 ** 2)
print(arr1% 2)

[-1  0  1  2  3  4  5  6  7  8]
[ 0 10 20 30 40 50 60 70 80 90]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]


In [131]:
arr1, arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]))

In [133]:
arr1+arr2#요소별로 연산

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [136]:
print(arr1-arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** arr2)
print(arr1 % arr2)

[-1.   0.1  1.2  2.3  3.4  4.5  5.6  6.7  7.8  8.9]
[0.  0.9 1.6 2.1 2.4 2.5 2.4 2.1 1.6 0.9]
[ 0.          1.11111111  2.5         4.28571429  6.66666667 10.
 15.         23.33333333 40.         90.        ]
[0.         1.         1.74110113 2.15766928 2.29739671 2.23606798
 2.04767251 1.79278996 1.51571657 1.24573094]
[0.  0.1 0.4 0.2 0.4 0.5 0.4 0.1 0.2 0.1]


In [137]:
arr1 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [138]:
arr1 > arr2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## 행렬

In [141]:
# 0행렬
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [143]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 일행렬

In [145]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [146]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 단위행렬

In [147]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [148]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [149]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 통계를 위한 연산

In [155]:
arr1 = np.arange(1, 11.0).reshape(5,2)
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

### sum

In [156]:
arr1.sum()

55.0

In [157]:
arr1.sum(axis=0)#column별로 

array([25., 30.])

In [158]:
arr1.sum(axis=1)#row단위

array([ 3.,  7., 11., 15., 19.])

#### mean

In [160]:
arr1.mean()

5.5

In [161]:
arr1.mean(axis=0)

array([5., 6.])

In [162]:
arr1.mean(axis=1)

array([1.5, 3.5, 5.5, 7.5, 9.5])

##### var

In [164]:
arr1.var()

8.25

In [165]:
arr1.var(axis=0)

array([8., 8.])

In [166]:
arr1.var(axis=1)

array([0.25, 0.25, 0.25, 0.25, 0.25])

# min

In [177]:
print(arr1.min())
print(arr1.min(axis=0))
print(arr1.min(axis=1))

1.0
[1. 2.]
[1. 3. 5. 7. 9.]


# max

In [178]:
arr1.max(axis=1)

array([ 2.,  4.,  6.,  8., 10.])

# consum

In [179]:
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [180]:
arr1.cumsum()

array([ 1.,  3.,  6., 10., 15., 21., 28., 36., 45., 55.])

In [184]:
arr1.cumsum(axis=0)

array([[ 1.,  2.],
       [ 4.,  6.],
       [ 9., 12.],
       [16., 20.],
       [25., 30.]])

# cumprod

In [185]:
arr1.cumprod(axis=0)

array([[1.00e+00, 2.00e+00],
       [3.00e+00, 8.00e+00],
       [1.50e+01, 4.80e+01],
       [1.05e+02, 3.84e+02],
       [9.45e+02, 3.84e+03]])

## std:표준편차

In [168]:
arr1.std(axis=1)

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [169]:
np.sqrt(arr1.var(axis=1))

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [170]:
np.log(arr1)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947],
       [1.94591015, 2.07944154],
       [2.19722458, 2.30258509]])

In [171]:
np.exp(arr1)#지수 e는 10의 0승 10의 1승...

array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04]])

In [172]:
2.5e+3

2500.0

In [173]:
2.5e-2

0.025

In [189]:
arr1 = np.arange(1,7).astype(np.float64).reshape(2, 3)
arr2 = np.arange(6,0,-1.0).astype(np.float64).reshape(3,2)
arr1, arr2

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[6., 5.],
        [4., 3.],
        [2., 1.]]))

#### 행렬 연산

In [192]:
arr1.shape, arr2.shape

((2, 3), (3, 2))

In [193]:
arr1 @ arr2

array([[20., 14.],
       [56., 41.]])

In [194]:
arr1.dot(arr2)

array([[20., 14.],
       [56., 41.]])

In [195]:
np.matmul(arr1,arr2)

array([[20., 14.],
       [56., 41.]])

# 전치

In [197]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [202]:
arr3 = np.arange(6).reshape(2,3)
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [203]:
arr1.shape, arr3.shape

((2, 3), (2, 3))

In [204]:
arr3.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [205]:
arr3.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [206]:
arr1.dot(arr3.T)

array([[ 8., 26.],
       [17., 62.]])

In [208]:
arr1 = np.arange(1,5).reshape(2,2)
arr1

array([[1, 2],
       [3, 4]])

In [211]:
arr2 = np.linalg.inv(arr1)
arr2

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [212]:
arr1.dot(arr2)# e-16승은 0이다  arr2는 단위 행렬이다

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [213]:
arr2.dot(arr1)#

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

# concat

In [214]:
arr1 = np.arange(4).reshape(2,2)
arr2 = np.arange(0,40,10).reshape(2,2)
arr1, arr2

(array([[0, 1],
        [2, 3]]),
 array([[ 0, 10],
        [20, 30]]))

In [216]:
np.concatenate((arr1,arr2), axis=0)

array([[ 0,  1],
       [ 2,  3],
       [ 0, 10],
       [20, 30]])

In [217]:
np.concatenate((arr1,arr2), axis=1)

array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])

In [218]:
#np.c_
np.c_[arr1,arr2]

array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])

1. 10개의  0벡터를 만들고 4번째와 5번째 Index의 값을 1로 한 후 (5,2)행렬을 만들어라

In [256]:
import numpy as np
arr1 = np.zeros(10)
arr1[[4,5]] = 1
arr1.reshape(5,2)

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

2. 10에서 30까지 2씩 증가하는 vector를 만들고 다음 list아 요소별 사칙연산을 하여라
a= [1.,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9]

In [233]:
arr2 = np.arange(10.0,30.0,2)
a= [1.,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9]
print(arr2+a)
print(arr2-a)
print(arr2*a)
print(arr2/a)

[11.  13.1 15.2 17.3 19.4 21.5 23.6 25.7 27.8 29.9]
[ 9.  10.9 12.8 14.7 16.6 18.5 20.4 22.3 24.2 26.1]
[10.  13.2 16.8 20.8 25.2 30.  35.2 40.8 46.8 53.2]
[10.         10.90909091 11.66666667 12.30769231 12.85714286 13.33333333
 13.75       14.11764706 14.44444444 14.73684211]


3.<1에서 100>까지 10개를 균등하게 분할하여 배열을 만들고, 각각의 합, 평균, 표준편차, 분산, 최소값, 최대값, 누적합, 누적곱을 구하여라

In [264]:
arr3 = np.arange(1,101).reshape(10,10)
#arr3 = np.linespace(1,100,10)
print(arr3.sum())
print(arr3.mean())
print(arr3.std())
print(arr3.var())
print(arr3.min())
print(arr3.max())
print(arr3.cumsum())
print(arr3.cumprod())

5050
50.5
28.86607004772212
833.25
1
100
[   1    3    6   10   15   21   28   36   45   55   66   78   91  105
  120  136  153  171  190  210  231  253  276  300  325  351  378  406
  435  465  496  528  561  595  630  666  703  741  780  820  861  903
  946  990 1035 1081 1128 1176 1225 1275 1326 1378 1431 1485 1540 1596
 1653 1711 1770 1830 1891 1953 2016 2080 2145 2211 2278 2346 2415 2485
 2556 2628 2701 2775 2850 2926 3003 3081 3160 3240 3321 3403 3486 3570
 3655 3741 3828 3916 4005 4095 4186 4278 4371 4465 4560 4656 4753 4851
 4950 5050]
[          1           2           6          24         120         720
        5040       40320      362880     3628800    39916800   479001600
  1932053504  1278945280  2004310016  2004189184  -288522240  -898433024
   109641728 -2102132736 -1195114496  -522715136   862453760  -775946240
  2076180480 -1853882368  1484783616 -1375731712 -1241513984  1409286144
   738197504 -2147483648 -2147483648           0           0           0
           0

In [ ]:
4. 0에서10까지 random한 값을 지닌 3x3 실수 행렬을 만들어라

In [271]:
np.random.seed(42)#42번쨰 렌덤함에서만 꺼내주세요
rand_n_arr = np.random.rand(3,3)
rand_n_arr*10

array([[3.74540119, 9.50714306, 7.31993942],
       [5.98658484, 1.5601864 , 1.5599452 ],
       [0.58083612, 8.66176146, 6.01115012]])

In [ ]:
5. 0에서 10까지 random한 값을 지닌 3x3 정수 행렬을 만들어라

In [272]:
rand_n_arr = np.random.randint(0, 10,(3,3))
rand_n_arr*10

array([[70, 20, 50],
       [40, 10, 70],
       [50, 10, 40]])

In [ ]:
6. 5x2 행렬을 만들고 standardizaion(정규화=표준화 하여라)

In [280]:

arr1 = np.linspace(-1000,1000, 5)
arr2 = np.linspace(0,10,5)

arr1 = arr1.reshape(5,-1)
arr2 = arr2.reshape(5,-1)
arr3 = np.concatenate((arr1,arr2), axis = 1)
arr3 

array([[-1000. ,     0. ],
       [ -500. ,     2.5],
       [    0. ,     5. ],
       [  500. ,     7.5],
       [ 1000. ,    10. ]])

In [281]:
arr1.std(), arr2.std()

(707.1067811865476, 3.5355339059327378)

In [285]:
arr4 = (arr3 - arr3.mean(axis = 0))/ arr3.std(axis=0)
arr4.mean(), arr4.std(), arr4.var()#평균:0 분산:1

(0.0, 0.9999999999999999, 0.9999999999999998)

In [ ]:
7. 5x2행렬을 만들고 Min-Max정규화 하여라

In [291]:
arr5=(arr3-arr3.min(axis=0))/(arr3.max(axis=0)-arr3.min(axis=0))
arr5

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])